# Format is $GHE_ORG_ID-$GHE_REPO_ID
sonar.projectKey=131014-1448271

# Format is $GHE_ORG_NAME/$GHE_ORG_REPO
sonar.projectName=ai-chip-toolchain/aiu-operator

# SonarQube Host URL
sonar.host.url=https://sonarqube-prod.apps.wdc-sonarqube-prod.core.cirrus.ibm.com

# SonarQube exclustions
sonar.exclusions=**/docs/**,**/jenkins/**,**/document/**,**/hack/**
