# +-------------------------------------------------------------------+
# | Copyright IBM Corp. 2025 All Rights Reserved                      |
# | PID 5698-SPR                                                      |
# +-------------------------------------------------------------------+

apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: spyre-operator
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spyre-operator
  namespace: system
  labels:
    control-plane: spyre-operator
spec:
  selector:
    matchLabels:
      control-plane: spyre-operator
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: spyre-operator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/arch"
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      serviceAccountName: spyre-operator
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - command:
        - /usr/bin/manager
        args:
        - --leader-elect
        image: controller:latest
        imagePullPolicy: Always
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 256Mi
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RELATED_IMAGE_SPYRE_OPERATOR
          value: SPYRE_OPERATOR_SHA256IMAGE_PLACEHOLDER
        - name: RELATED_IMAGE_KUBE_RBAC_PROXY
          value: registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:fcb3b8ab93dfb5ef2b290e39ea5899dbb5e0c6d430370b8d281e59e74d94d749
        ports:
        - name: metrics
          containerPort: 8080
      terminationGracePeriodSeconds: 10
