# Copyright (c) 2025, 2026 IBM Corp.
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spyre-metrics-exporter
  name: spyre-metrics-exporter
  namespace: "FILLED BY THE OPERATOR"
  annotations:
    prometheus.io/target: "true"
spec:
  selector:
    app: spyre-metrics-exporter
  ports:
  - name: spyre-metrics
    port: 8082
    protocol: TCP
    targetport: spyre-metrics
  type: ClusterIP
