{
 "title": "Spyre Card Info",
 "panels": [
  {
   "title": "Total Number",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(spyre_info_pci_cfg)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Card Info",
   "type": "table",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node, MaxPayload, MaxReadReq, Speed, Width) (spyre_info_pci_cfg)"
    }
   ]
  }
 ]
}
{
 "title": "Spyre Card Allocation",
 "panels": [
  {
   "title": "Total in-use",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(spyre_allocation)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "by Namespace",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(spyre_allocation) by (exported_namespace)",
     "legendFormat": "{{exported_namespace}}"
    }
   ]
  },
  {
   "title": "by Node",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(spyre_allocation) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}
{
 "title": "Spyre Card Usage",
 "panels": [
  {
   "title": "DMO::MCI Read Cycles",
   "type": "graph",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(irate(spyre_usage_dmo_dur_mci_read{node=~\"$node\", exported_namespace=~\"$namespace\"}[5m])) by (exported_pod, exported_namespace)",
     "legendFormat": "{{exported_pod}}/{{exported_namespace}}"
    }
   ]
  },
  {
   "title": "DMO::MCI Write Cycles",
   "type": "graph",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(irate(spyre_usage_dmo_dur_mci_write{node=~\"$node\", exported_namespace=~\"$namespace\"}[5m])) by (exported_pod, exported_namespace)",
     "legendFormat": "{{exported_pod}}/{{exported_namespace}}"
    }
   ]
  }
 ]
}