# Copyright (c) 2025, 2026 IBM Corp.
# SPDX-License-Identifier: Apache-2.0
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: spyre-operator
  namespace: spyre-operator
spec:
  channel: "fast-v1.3"
  name: spyre-operator
  source: ibm-spyre-operators
  sourceNamespace: openshift-marketplace
