#  Copyright (c) 2025, 2026 IBM Corp.
#  SPDX-License-Identifier: Apache-2.0
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spyre-health-checker
  namespace: "FILLED BY THE OPERATOR"
  labels:
    k8s-app: spyre-health-checker-monitor
spec:
  endpoints:
  - interval: 30s
    port: metrics
    scheme: http
  selector:
    matchLabels:
      app: spyre-health-checker
