# Copyright (c) 2025, 2026 IBM Corp.
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ConfigMap
metadata:
  name: secondary-scheduler-config
  namespace: openshift-secondary-scheduler-operator
data:
  "config.yaml": |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
      - schedulerName: spyre-scheduler
        plugins:
          filter:
            enabled:
              - name: SpyrePlugin
          reserve:
            enabled:
              - name: SpyrePlugin
