# Copyright (c) 2025, 2026 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

resources:
- spyre_v1alpha1_spyreclusterpolicy.yaml
- spyre_v1alpha1_spyrenodestate.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
