/*
 * +-------------------------------------------------------------------+
 * | Copyright (c) 2025, 2026 IBM Corp.                                |
 * | SPDX-License-Identifier: Apache-2.0                               |
 * +-------------------------------------------------------------------+
 */

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Allocation) DeepCopyInto(out *Allocation) {
	*out = *in
	if in.DeviceList != nil {
		in, out := &in.DeviceList, &out.DeviceList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Pod != nil {
		in, out := &in.Pod, &out.Pod
		*out = new(Pod)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Allocation.
func (in *Allocation) DeepCopy() *Allocation {
	if in == nil {
		return nil
	}
	out := new(Allocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardManagementConfig) DeepCopyInto(out *CardManagementConfig) {
	*out = *in
	if in.SpyreFilter != nil {
		in, out := &in.SpyreFilter, &out.SpyreFilter
		*out = new(string)
		**out = **in
	}
	if in.PfRunnerImage != nil {
		in, out := &in.PfRunnerImage, &out.PfRunnerImage
		*out = new(string)
		**out = **in
	}
	if in.VfRunnerImage != nil {
		in, out := &in.VfRunnerImage, &out.VfRunnerImage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardManagementConfig.
func (in *CardManagementConfig) DeepCopy() *CardManagementConfig {
	if in == nil {
		return nil
	}
	out := new(CardManagementConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardManagementSpec) DeepCopyInto(out *CardManagementSpec) {
	*out = *in
	in.DeploymentConfig.DeepCopyInto(&out.DeploymentConfig)
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(CardManagementConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardManagementSpec.
func (in *CardManagementSpec) DeepCopy() *CardManagementSpec {
	if in == nil {
		return nil
	}
	out := new(CardManagementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentConfig) DeepCopyInto(out *DeploymentConfig) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentConfig.
func (in *DeploymentConfig) DeepCopy() *DeploymentConfig {
	if in == nil {
		return nil
	}
	out := new(DeploymentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceConfigSpec) DeepCopyInto(out *DeviceConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceConfigSpec.
func (in *DeviceConfigSpec) DeepCopy() *DeviceConfigSpec {
	if in == nil {
		return nil
	}
	out := new(DeviceConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePluginSpec) DeepCopyInto(out *DevicePluginSpec) {
	*out = *in
	out.DeviceConfigSpec = in.DeviceConfigSpec
	in.DeploymentConfig.DeepCopyInto(&out.DeploymentConfig)
	if in.InitContainer != nil {
		in, out := &in.InitContainer, &out.InitContainer
		*out = new(ExternalInitContainerSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePluginSpec.
func (in *DevicePluginSpec) DeepCopy() *DevicePluginSpec {
	if in == nil {
		return nil
	}
	out := new(DevicePluginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePluginsStateStatus) DeepCopyInto(out *DevicePluginsStateStatus) {
	*out = *in
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make(InterfaceExts, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePluginsStateStatus.
func (in *DevicePluginsStateStatus) DeepCopy() *DevicePluginsStateStatus {
	if in == nil {
		return nil
	}
	out := new(DevicePluginsStateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalInitContainerSpec) DeepCopyInto(out *ExternalInitContainerSpec) {
	*out = *in
	if in.ExecutePolicy != nil {
		in, out := &in.ExecutePolicy, &out.ExecutePolicy
		*out = new(ExecutePolicy)
		**out = **in
	}
	in.DeploymentConfig.DeepCopyInto(&out.DeploymentConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalInitContainerSpec.
func (in *ExternalInitContainerSpec) DeepCopy() *ExternalInitContainerSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalInitContainerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckerSpec) DeepCopyInto(out *HealthCheckerSpec) {
	*out = *in
	in.DeploymentConfig.DeepCopyInto(&out.DeploymentConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckerSpec.
func (in *HealthCheckerSpec) DeepCopy() *HealthCheckerSpec {
	if in == nil {
		return nil
	}
	out := new(HealthCheckerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Interface) DeepCopyInto(out *Interface) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Interface.
func (in *Interface) DeepCopy() *Interface {
	if in == nil {
		return nil
	}
	out := new(Interface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceExt) DeepCopyInto(out *InterfaceExt) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceExt.
func (in *InterfaceExt) DeepCopy() *InterfaceExt {
	if in == nil {
		return nil
	}
	out := new(InterfaceExt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in InterfaceExts) DeepCopyInto(out *InterfaceExts) {
	{
		in := &in
		*out = make(InterfaceExts, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceExts.
func (in InterfaceExts) DeepCopy() InterfaceExts {
	if in == nil {
		return nil
	}
	out := new(InterfaceExts)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsExporterSpec) DeepCopyInto(out *MetricsExporterSpec) {
	*out = *in
	in.DeploymentConfig.DeepCopyInto(&out.DeploymentConfig)
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsExporterSpec.
func (in *MetricsExporterSpec) DeepCopy() *MetricsExporterSpec {
	if in == nil {
		return nil
	}
	out := new(MetricsExporterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Pod) DeepCopyInto(out *Pod) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Pod.
func (in *Pod) DeepCopy() *Pod {
	if in == nil {
		return nil
	}
	out := new(Pod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodValidatorSpec) DeepCopyInto(out *PodValidatorSpec) {
	*out = *in
	in.DeploymentConfig.DeepCopyInto(&out.DeploymentConfig)
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodValidatorSpec.
func (in *PodValidatorSpec) DeepCopy() *PodValidatorSpec {
	if in == nil {
		return nil
	}
	out := new(PodValidatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Reservation) DeepCopyInto(out *Reservation) {
	*out = *in
	if in.PodsUnderScheduling != nil {
		in, out := &in.PodsUnderScheduling, &out.PodsUnderScheduling
		*out = make([]Pod, len(*in))
		copy(*out, *in)
	}
	if in.DeviceSets != nil {
		in, out := &in.DeviceSets, &out.DeviceSets
		*out = make([][]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Reservation.
func (in *Reservation) DeepCopy() *Reservation {
	if in == nil {
		return nil
	}
	out := new(Reservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulerSpec) DeepCopyInto(out *SchedulerSpec) {
	*out = *in
	in.DeploymentConfig.DeepCopyInto(&out.DeploymentConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulerSpec.
func (in *SchedulerSpec) DeepCopy() *SchedulerSpec {
	if in == nil {
		return nil
	}
	out := new(SchedulerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpyreClusterPolicy) DeepCopyInto(out *SpyreClusterPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpyreClusterPolicy.
func (in *SpyreClusterPolicy) DeepCopy() *SpyreClusterPolicy {
	if in == nil {
		return nil
	}
	out := new(SpyreClusterPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpyreClusterPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpyreClusterPolicyList) DeepCopyInto(out *SpyreClusterPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SpyreClusterPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpyreClusterPolicyList.
func (in *SpyreClusterPolicyList) DeepCopy() *SpyreClusterPolicyList {
	if in == nil {
		return nil
	}
	out := new(SpyreClusterPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpyreClusterPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpyreClusterPolicySpec) DeepCopyInto(out *SpyreClusterPolicySpec) {
	*out = *in
	in.DevicePlugin.DeepCopyInto(&out.DevicePlugin)
	in.CardManagement.DeepCopyInto(&out.CardManagement)
	in.MetricsExporter.DeepCopyInto(&out.MetricsExporter)
	in.Scheduler.DeepCopyInto(&out.Scheduler)
	in.PodValidator.DeepCopyInto(&out.PodValidator)
	in.HealthChecker.DeepCopyInto(&out.HealthChecker)
	if in.ExperimentalMode != nil {
		in, out := &in.ExperimentalMode, &out.ExperimentalMode
		*out = make([]SpyreClusterPolicyExperimentalMode, len(*in))
		copy(*out, *in)
	}
	if in.LogLevel != nil {
		in, out := &in.LogLevel, &out.LogLevel
		*out = new(string)
		**out = **in
	}
	if in.SkipUpdateComponents != nil {
		in, out := &in.SkipUpdateComponents, &out.SkipUpdateComponents
		*out = make([]Component, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpyreClusterPolicySpec.
func (in *SpyreClusterPolicySpec) DeepCopy() *SpyreClusterPolicySpec {
	if in == nil {
		return nil
	}
	out := new(SpyreClusterPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpyreClusterPolicyStatus) DeepCopyInto(out *SpyreClusterPolicyStatus) {
	*out = *in
	in.DevicePlugins.DeepCopyInto(&out.DevicePlugins)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpyreClusterPolicyStatus.
func (in *SpyreClusterPolicyStatus) DeepCopy() *SpyreClusterPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(SpyreClusterPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpyreInterface) DeepCopyInto(out *SpyreInterface) {
	*out = *in
	if in.Vfs != nil {
		in, out := &in.Vfs, &out.Vfs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpyreInterface.
func (in *SpyreInterface) DeepCopy() *SpyreInterface {
	if in == nil {
		return nil
	}
	out := new(SpyreInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in SpyreInterfaces) DeepCopyInto(out *SpyreInterfaces) {
	{
		in := &in
		*out = make(SpyreInterfaces, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpyreInterfaces.
func (in SpyreInterfaces) DeepCopy() SpyreInterfaces {
	if in == nil {
		return nil
	}
	out := new(SpyreInterfaces)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpyreNodeState) DeepCopyInto(out *SpyreNodeState) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpyreNodeState.
func (in *SpyreNodeState) DeepCopy() *SpyreNodeState {
	if in == nil {
		return nil
	}
	out := new(SpyreNodeState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpyreNodeState) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpyreNodeStateList) DeepCopyInto(out *SpyreNodeStateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SpyreNodeState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpyreNodeStateList.
func (in *SpyreNodeStateList) DeepCopy() *SpyreNodeStateList {
	if in == nil {
		return nil
	}
	out := new(SpyreNodeStateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpyreNodeStateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpyreNodeStateSpec) DeepCopyInto(out *SpyreNodeStateSpec) {
	*out = *in
	if in.SpyreInterfaces != nil {
		in, out := &in.SpyreInterfaces, &out.SpyreInterfaces
		*out = make(SpyreInterfaces, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SpyreSSAInterfaces != nil {
		in, out := &in.SpyreSSAInterfaces, &out.SpyreSSAInterfaces
		*out = make(SpyreSSAInterfaces, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpyreNodeStateSpec.
func (in *SpyreNodeStateSpec) DeepCopy() *SpyreNodeStateSpec {
	if in == nil {
		return nil
	}
	out := new(SpyreNodeStateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpyreNodeStateStatus) DeepCopyInto(out *SpyreNodeStateStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UnhealthyDevices != nil {
		in, out := &in.UnhealthyDevices, &out.UnhealthyDevices
		*out = make([]UnhealthyDevice, len(*in))
		copy(*out, *in)
	}
	if in.AllocationList != nil {
		in, out := &in.AllocationList, &out.AllocationList
		*out = make([]Allocation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Reservations != nil {
		in, out := &in.Reservations, &out.Reservations
		*out = make(map[string]Reservation, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpyreNodeStateStatus.
func (in *SpyreNodeStateStatus) DeepCopy() *SpyreNodeStateStatus {
	if in == nil {
		return nil
	}
	out := new(SpyreNodeStateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpyreSSAInterface) DeepCopyInto(out *SpyreSSAInterface) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpyreSSAInterface.
func (in *SpyreSSAInterface) DeepCopy() *SpyreSSAInterface {
	if in == nil {
		return nil
	}
	out := new(SpyreSSAInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in SpyreSSAInterfaces) DeepCopyInto(out *SpyreSSAInterfaces) {
	{
		in := &in
		*out = make(SpyreSSAInterfaces, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpyreSSAInterfaces.
func (in SpyreSSAInterfaces) DeepCopy() SpyreSSAInterfaces {
	if in == nil {
		return nil
	}
	out := new(SpyreSSAInterfaces)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnhealthyDevice) DeepCopyInto(out *UnhealthyDevice) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnhealthyDevice.
func (in *UnhealthyDevice) DeepCopy() *UnhealthyDevice {
	if in == nil {
		return nil
	}
	out := new(UnhealthyDevice)
	in.DeepCopyInto(out)
	return out
}
