# Copyright (c) 2025, 2026 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spyre-card-management-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spyre-card-management-clusterrole
subjects:
- kind: ServiceAccount
  name: spyre-card-management
  namespace: "FILLED BY THE OPERATOR"
