# Copyright (c) 2025, 2026 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: vf
spec:
  machineConfigSelector:
    matchExpressions:
    - key: machineconfiguration.openshift.io/role
      operator: In
      values:
      - vf
      - worker
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/vf: ""
  paused: false
