name: CRC Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  crc:
    runs-on: ubuntu-latest

    steps:
    - name: Confirm new workflow
      run: echo "NEW WORKFLOW RUNNING"
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libvirt-daemon qemu-kvm

    - name: Install CRC
      run: |
        curl -L -o crc.tar.xz https://mirror.openshift.com/pub/openshift-v4/clients/crc/latest/crc-linux-amd64.tar.xz

    - name: Verify download
      run: |
        ls -lh crc.tar.xz

    - name: Extract CRC
      run: |
        tar -xvf crc.tar.xz
        sudo mv crc-linux-*/crc /usr/local/bin/

    - name: Setup CRC
      run: crc setup || true

    - name: Start CRC
      run: crc start || true

    - name: Debug
      run: crc logs || true
